repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: flake8 enforcement
        entry: flake8
        args: ["--config=setup.cfg"]
        exclude: /(env|venv|src_local)/
        language: python
        types: [python]
      - id: isort
        name: isort
        description: isort enforcement
        entry: isort .
        language: python
        types: [python]
